from PrivPwcApprox import *
from AdaptApprox import *

plt.figure(figsize = (16, 8))
solver = PrivatePiecewiseApprox((-1, 1), [-1, 1], 'Fourier', degree = 2)
plt.subplot(2, 2, 1)
func = lambda x: 20*np.sin(4*np.pi*x)+10*np.cos(8*np.pi*x)
approx, priv = adaptive_poly_approx(func = func, interval = (-1, 1), basis = 'Fourier', degree = 2)
plot_1D_1D(func, approx, priv, solver)
plt.subplot(2, 2, 2)
func = lambda x: 80*np.sin(4*np.pi*x)+40*np.cos(8*np.pi*x)
approx, priv = adaptive_poly_approx(func = func, interval = (-1, 1), basis = 'Fourier', degree = 2)
plot_1D_1D(func, approx, priv, solver)
plt.subplot(2, 2, 3)
func = lambda x: 320*np.sin(4*np.pi*x)+160*np.cos(8*np.pi*x)
approx, priv = adaptive_poly_approx(func = func, interval = (-1, 1), basis = 'Fourier', degree = 2)
plot_1D_1D(func, approx, priv, solver)
plt.subplot(2, 2, 4)
func = lambda x: 1280*np.sin(4*np.pi*x)+640*np.cos(8*np.pi*x)
approx, priv = adaptive_poly_approx(func = func, interval = (-1, 1), basis = 'Fourier', degree = 2)
plot_1D_1D(func, approx, priv, solver)
plt.tight_layout()
plt.show()
